# Exemple à copier en 11-secret.yaml AVEC vos valeurs (et ne pas commiter)
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: workshop
type: Opaque
stringData:
  DB_USER: app
  DB_PASS: changeMe123
